name: Typecheck
on: push
permissions:
  contents: read

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - run: yarn
      - run: yarn test:types
